name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  google_fonts: ^5.0.1
  
  http: ^1.2.2
  dartz: ^0.10.1
  cached_network_image: ^3.4.0
  provider: ^6.1.2

  about:
    path: ../about
  flutter_rating_bar: ^4.0.1
  sqflite_sqlcipher: ^3.1.0+1
  encrypt: ^5.0.3
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  firebase_crashlytics: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  test: ^1.25.2

flutter:  
  assets:
    - certificates/certificates.pem
