// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWVAf1TMwMImzHlDixzEC7kxZVZiGzaho',
    appId: '1:186830727783:web:32e91818991e06afc082c2',
    messagingSenderId: '186830727783',
    projectId: 'ditonton-80517',
    authDomain: 'ditonton-80517.firebaseapp.com',
    storageBucket: 'ditonton-80517.appspot.com',
    measurementId: 'G-446L1CNHL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBntRaSRILE1Tka0UKh-Am4AkE5rz-_eBk',
    appId: '1:186830727783:android:5970cb4f8318a4dac082c2',
    messagingSenderId: '186830727783',
    projectId: 'ditonton-80517',
    storageBucket: 'ditonton-80517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKX7sjsMv92DZvkhKrHd-wzQkhfRxTn9M',
    appId: '1:186830727783:ios:0d845cc548644a9fc082c2',
    messagingSenderId: '186830727783',
    projectId: 'ditonton-80517',
    storageBucket: 'ditonton-80517.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
